version: "3.8"

services:
  mysql:
    image: mysql:8.3
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
      - --default-authentication-plugin=mysql_native_password
      - --max-allowed-packet=512MB
    networks:
      - wanzeller_network
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE_FILE: /run/secrets/RADICAL
      MYSQL_USER_FILE: /run/secrets/USUARIO
      MYSQL_PASSWORD_FILE: /run/secrets/SENHA
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/SENHA
    secrets:
      - RADICAL
      - USUARIO
      - SENHA
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

volumes:
  mysql_data:
    external: true

secrets:
  RADICAL:
    external: true
  USUARIO:
    external: true
  SENHA:
    external: true

networks:
  wanzeller_network:
    external: true