version: "3.8"

services:
  phpmyadmin:
    image: phpmyadmin:latest
    networks:
      - wanzeller_network
      - traefik_public
    environment:
      PMA_HOSTS: mysql
      PMA_ARBITRARY: 0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.phpmyadmin.rule=Host(`mysql.wendersonwanzeller.com`)
        - traefik.http.routers.phpmyadmin.entrypoints=websecure
        - traefik.http.routers.phpmyadmin.tls.certresolver=le
        - traefik.http.services.phpmyadmin.loadbalancer.server.port=80

networks:
  wanzeller_network:
    external: true
  traefik_public:
    external: true