version: "3.8"

services:
  mysql:
    image: mysql:8.3
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
      - --default-authentication-plugin=mysql_native_password
      - --max-allowed-packet=512MB
    networks:
      - wanzeller_network
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/GLOBAL_SECRET
      MYSQL_DATABASE: ${RADICAL}
      MYSQL_USER: ${USER_NAME}
      MYSQL_PASSWORD_FILE: /run/secrets/GLOBAL_SECRET
    secrets:
      - GLOBAL_SECRET
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  phpmyadmin:
    image: phpmyadmin:latest
    networks:
      - wanzeller_network
      - traefik_public
    environment:
      PMA_HOSTS: mysql
      PMA_ARBITRARY: 0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.phpmyadmin.rule=Host(`mysql.${DOMAIN}`)
        - traefik.http.routers.phpmyadmin.entrypoints=websecure
        - traefik.http.routers.phpmyadmin.tls.certresolver=le
        - traefik.http.services.phpmyadmin.loadbalancer.server.port=80

volumes:
  mysql_data:
    external: true

secrets:
  GLOBAL_SECRET:
    external: true

networks:
  wanzeller_network:
    external: true
  traefik_public:
    external: true